[tool.poetry]
name = "apperception"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
psycopg2 = "^2.9.3"
PyPika = "^0.48.9"
PyYAML = "^6.0"
dill = "^0.3.4"
PyQt5 = "^5.15.6"
pyquaternion = "^0.9.9"
numpy = "^1.22.3"
matplotlib = "^3.5.1"
uncompyle6 = "^3.8.0"
Pillow = "^9.1.0"
torch = "^1.11.0"
opencv-python = "^4.5.5"
pandas = "^1.4.2"
decompyle3 = "^3.8.0"

[tool.poetry.dev-dependencies]
jupyterlab = "^3.3.2"
autoflake = "^1.4"
black = "^22.3.0"
isort = "^5.10.1"
autopep8 = "^1.6.0"
flake8 = "^4.0.1"
mypy = "^0.942"
types-PyYAML = "^6.0.5"
types-psycopg2 = "^2.9.9"
pyright = "^1.1.235"
astpretty = "^2.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
verbose = true

[tool.autopep8]
in-place = true
recursive = true
aggressive = 3
verbose = 2
