\i facingRelative.sql;
\i getX.sql;
\i getY.sql;
\i getZ.sql;
\i roadDirection.sql;
\i overlap.sql;
\i viewAngle.sql;
\i geoContained.sql;
\i geoContainedMargin.sql;
\i distance.sql;
\i convertCamera.sql;
\i operators.sql;
\i roadSegment.sql;
\i angleBetween.sql;
\i angleExcluding.sql
\i minDistance.sql;
\i objectBBox.sql;
\i minDistance.sql;
\i ahead.sql