/* viewAngle:
    params: position(location) to view, view_point_heading, view_point */
DROP FUNCTION viewAngle(geometry, real, geometry);
CREATE OR REPLACE FUNCTION viewAngle(position geometry, view_point_heading real, view_point geometry)
    RETURNS real
    AS $$
    SELECT ST_Azimuth(position, view_point) - view_point_heading; 
    /* this is auto generated by copilot, double check if this is the correct function to use*/
    $$
    LANGUAGE SQL IMMUTABLE;

DROP FUNCTION IF EXISTS viewAngle(tgeompoint, real, geometry, timestamptz);
CREATE OR REPLACE FUNCTION viewAngle(object_trajectory tgeompoint, camera_heading real, camera_location geometry, _time timestamptz) RETURNS real AS
$BODY$
BEGIN
  RETURN viewAngle();
END
$BODY$
LANGUAGE 'plpgsql' ;