/* Generated by github copilot
    viewAngle:
    params: position(location) to view, view_point_heading, view_point 
*/
DROP FUNCTION IF EXISTS viewAngle(geometry, real, geometry);
CREATE OR REPLACE FUNCTION viewAngle(view_point geometry, view_point_heading real, pos geometry) RETURNS real AS 
$BODY$
BEGIN
    RETURN CAST((ST_Azimuth(view_point, pos) * 180 / PI() - view_point_heading + 360) AS numeric) % 360; 
END
$BODY$
LANGUAGE 'plpgsql' ;

DROP FUNCTION IF EXISTS viewAngle(tgeompoint, real, geometry, timestamptz);
CREATE OR REPLACE FUNCTION viewAngle(object_trajectory tgeompoint, camera_heading real, camera_location geometry, _time timestamptz) RETURNS real AS
$BODY$
BEGIN
  RETURN viewAngle(camera_location, camera_heading, valueAtTimestamp(object_trajectory, _time));
END
$BODY$
LANGUAGE 'plpgsql' ;