name: Clean Up and Format
on:
  push:
    branches-ignore:
      - 'main'
      - 'dev'

jobs:
  clean-up:
    name: Clean Up Python Notebooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT || github.token }}

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Cleanup ipynb output
        run: |
          pip install nbconvert
          python -m jupyter nbconvert --clear-output --inplace benchmarks/**/*.ipynb benchmarks/*.ipynb
      
      - name: Commit clean up changes
        run: ./scripts/commit-and-push.sh "[CI] cleanup python notebooks"
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT || github.token }}

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      
      - name: Install Dependencies
        run: pip install autoflake autopep8 black isort flake8
      
      - name: Fix lint with autoflake
        run: python -m autoflake --recursive --in-place --remove-all-unused-imports --ignore-init-module-imports --expand-star-imports apperception

      - name: Fix lint with autopep8
        run: python -m autopep8 --verbose --recursive --in-place --aggressive --aggressive apperception
        
      - name: Format with black
        run: python -m black --config pyproject.toml apperception
      
      - name: Sort imports with isort
        run: python -m isort apperception
      
      - name: Commit formatted changes
        run: ./scripts/commit-and-push.sh "[CI] format"
      
      - name: Analyze the code with flake8
        if: always()
        run: python -m flake8 apperception
