name: Test
on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      mobilitydb:
        image: mobilitydb/mobilitydb:14-3.2-1
        ports:
          - 25440:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mobilitydb-road-1:
        image: mobilitydb/mobilitydb:14-3.2-1
        ports:
          - 25441:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mobilitydb-road-2:
        image: mobilitydb/mobilitydb:14-3.2-1
        ports:
          - 25442:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mobilitydb-reset:
        image: mobilitydb/mobilitydb:14-3.2-1
        ports:
          - 25443:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mobilitydb-import:
        image: mobilitydb/mobilitydb:14-3.2-1
        ports:
          - 25444:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mobilitydb-sql:
        image: mobilitydb/mobilitydb:14-3.2-1
        ports:
          - 25445:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT || github.token }}
          submodules: recursive

      # - name: Set up Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: "3.10.6"
      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          init-shell: none
      # - uses: conda-incubator/setup-miniconda@v2
      #   with:
      #     # auto-activate-base: true
      #     activate-environment: "apperception"
      - name: Check Python Versions
        shell: micromamba-shell {0}
        run: |
          python --version
          python3 --version
          which python
          which python3
          which pip
          which pip3
          which poetry

      # - name: Install Conda Environment
      #   run: conda env update --file environment.yml --prune

      # - name: Install and configure Poetry
      #   uses: snok/install-poetry@v1
      #   with:
      #     virtualenvs-create: true
      #     virtualenvs-in-project: true
      #     installer-parallel: true

      # - name: Cache Poetry virtualenv
      #   uses: actions/cache@v3
      #   id: cached-poetry-dependencies 
      #   with:
      #     path: .venv
      #     key: poetry-venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install Dependencies
        shell: micromamba-shell {0}
        # if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --without dev --with test
      
      # - name: Install lap (Hack)
      #   shell: micromamba-shell {0}
      #   run: |
      #     pip install --upgrade pip
      #     pip install lap
      #     # git clone https://github.com/gatagat/lap.git
      #     # pushd lap
      #     #   python3 setup.py build
      #     #   python3 setup.py install
      #     # popd
      
      - name: Check Installed Packages
        shell: micromamba-shell {0}
        run: pip list

      - name: Extend MobilityDB with User-Defined functions
        shell: micromamba-shell {0}
        run: |
          pushd pg_extender
          python ../scripts/generate_pg_extender.py
          cat install.sql
          psql -h localhost -p 25440 -d mobilitydb -U docker -c "SET client_min_messages TO WARNING;" -c "\i install.sql;"
          psql -h localhost -p 25441 -d mobilitydb -U docker -c "SET client_min_messages TO WARNING;" -c "\i install.sql;"
          psql -h localhost -p 25442 -d mobilitydb -U docker -c "SET client_min_messages TO WARNING;" -c "\i install.sql;"
          psql -h localhost -p 25443 -d mobilitydb -U docker -c "SET client_min_messages TO WARNING;" -c "\i install.sql;"
          psql -h localhost -p 25444 -d mobilitydb -U docker -c "SET client_min_messages TO WARNING;" -c "\i install.sql;"
          popd
        env:
          PGPASSWORD: docker
      
      - name: Ingest data
        shell: micromamba-shell {0}
        run: |
          python ./scripts/ingest_road.py
          python ./scripts/import_tables.py
          jupyter nbconvert --execute --to notebook ./scripts/optimized-scenic/add_attributes.ipynb
        env:
          AP_PORT: 25440
      
      - name: Generate Image data
        shell: micromamba-shell {0}
        run: python scripts/fake-images.py
      
      - name: Unit Test
        shell: micromamba-shell {0}
        run: pytest --cov=apperception --cov-report=xml tests
        env:
          AP_PORT: 25440
          AP_PORT_ROAD_1: 25441
          AP_PORT_ROAD_2: 25442
          AP_PORT_RESET: 25443
          AP_PORT_IMPORT: 25444
          AP_PORT_SQL: 25445
      
      - name: Upload coverage reports to Codecov
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${{ secrets.CODECOV_TOKEN }}
