name: Test2
on:
  push:

jobs:
  test2:
    name: Test2
    runs-on: ubuntu-latest
    services:
      mobilitydbtest:
        image: mobilitydb/mobilitydb:14-3.2-1
        ports:
          - 25440:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT || github.token }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.6"

      - name: Extend MobilityDB with User-Defined functions
        run: |
          docker exec -it mobilitydbtest rm -rf /pg_extender
          docker cp pg_extender mobilitydbtest:/pg_extender
          docker exec -it -w /pg_extender mobilitydbtest python3 install.py
        env:
          PGPASSWORD: docker
      
      - name: Ingest data
        run: |
          poetry run python -c "from apperception.utils import ingest_road; from apperception.database import database; ingest_road(database, './data/scenic/road-network/boston-seaport')"
        env:
          AP_PORT: 25440